### ISSUE TITLE
Auto update for plugins.

### ISSUE THREAD

**Issue by Versatile-BFG** [splewis/csgo-retakes#9] opened 2015-02-05 04:50 UTC
As SM1.7 is out could you add auto update to all the retake plugins. So if you change something it will be pushed out to servers.

Also it would help if there was an option for updating the spawn files. Some people might not want them to auto update but others [like me] would like them to be updated. =)

**Comment by splewis** [comment] 2015-02-05 07:02
The updating spawn idea is pretty interesting since I could just make 2 hosting urls where 1 is just the base plugin and the other is the base plugin + all map configs I support and there's a cvar to pick which one.

I don't think I want to do any auto-update stuff until it's more mature, although I see the plugin as mostly complete.

**Comment by splewis** [comment] 2017-01-29 05:25
Duplicate of #38

**Closed by splewis** 2017-01-29 05:25 UTC
Labels: enhancement
