### ISSUE TITLE
t's have more players than ct's

### ISSUE THREAD

**Issue by xBrandonGx97** [splewis/csgo-retakes#195] opened 2019-05-17 14:27 UTC
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
5v4 (ct's have 5 and t 's have 4)

### Actual behavior
(t's have 5 and ct's have 4)

### Steps to reproduce
- Plugin version: latest - using batmen weapon allocator
- Sourcemod version: 1.7.3-dev+5283
- Steps to reproduce (please be specific): I don't know, it happens all the time.

**Comment by splewis** [comment] 2019-05-22 00:52
> Steps to reproduce (please be specific): I don't know, it happens all the time.

No really enough info to help then. See also: https://github.com/splewis/csgo-retakes/issues/196#issuecomment-494610793

> Sourcemod version: 1.7.3-dev+5283

That's... definitely too old. Updating that should be the first thing you did. I'm surprised that works at all.

**Comment by splewis** [comment] 2019-11-03 19:10
Closing since there's not enough info to reproduce. https://github.com/splewis/csgo-retakes/issues/204 might be relevant, though.

**Closed by splewis** 2019-11-03 19:10 UTC
Labels: user help
