### ISSUE TITLE
Server crashing when map change 

### ISSUE THREAD

**Issue by gerrard9099** [splewis/csgo-retakes#71] opened 2016-04-22 17:56 UTC
**Title says it all,
SM LOG:**

L 04/22/2016 - 18:38:02: -------- Mapchange to de_dust2 --------
L 04/22/2016 - 18:38:02: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_rcon_log") (value "1")
L 04/22/2016 - 18:38:02: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_minrate") (value "128000")
L 04/22/2016 - 18:38:02: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_maxrate") (value "0")
L 04/22/2016 - 18:38:02: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_mincmdrate") (value "128")
L 04/22/2016 - 18:38:31: [basecommands.smx] "Lanex:)<2><removed Steamid><>" changed map to "inf"
L 04/22/2016 - 18:38:34: [SM] Changed map to "inf"
L 04/22/2016 - 18:38:39: -------- Mapchange to de_inferno --------
L 04/22/2016 - 18:38:39: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_rcon_log") (value "1")
L 04/22/2016 - 18:38:40: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_minrate") (value "128000")
L 04/22/2016 - 18:38:40: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_maxrate") (value "0")
L 04/22/2016 - 18:38:40: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_mincmdrate") (value "128")
L 04/22/2016 - 18:56:22: -------- Mapchange to de_nuke --------
L 04/22/2016 - 18:56:22: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_rcon_log") (value "1")
L 04/22/2016 - 18:56:22: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_minrate") (value "128000")
L 04/22/2016 - 18:56:22: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_maxrate") (value "0")
L 04/22/2016 - 18:56:22: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_mincmdrate") (value "128")
L 04/22/2016 - 18:59:43: [basecommands.smx] "farlig mAnN<5><removed Steamid><>" kicked "EGM<11><removed Steamid><>" (reason "")
L 04/22/2016 - 19:06:36: [basecommands.smx] "farlig mAnN<5><removed Steamid><>" kicked "Micr0<14><removed Steamid><>" (reason "")
L 04/22/2016 - 19:07:26: [basecommands.smx] "Suh dude. @Lanex:)<6><removed Steamid><>" kicked "Itz Quexï Brah<12><removed Steamid><>" (reason "")
L 04/22/2016 - 19:16:21: -------- Mapchange to de_train --------
L 04/22/2016 - 19:16:21: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_rcon_log") (value "1")
L 04/22/2016 - 19:16:21: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_minrate") (value "128000")
L 04/22/2016 - 19:16:21: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_maxrate") (value "0")
L 04/22/2016 - 19:16:21: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_mincmdrate") (value "128")

**Csgo-ds log:**

L 04/22/2016 - 19:34:47: "Depressed Snake<18><removed Steamid><>" triggered "weaponstats" (weapon "ak47") (shots "21") (hits "4") (kills "0") (headshots "0") (tks "0") (damage "105") (deaths "0")
L 04/22/2016 - 19:34:47: "Depressed Snake<18><removed Steamid><>" triggered "weaponstats2" (weapon "ak47") (head "0") (chest "1") (stomach "0") (leftarm "0") (rightarm "2") (leftleg "1") (rightleg "0")
L 04/22/2016 - 19:34:52: "EGM<16><removed Steamid><CT>" triggered "Begin_Bomb_Defuse_With_Kit"
L 04/22/2016 - 19:34:59: "EGM<16><removed Steamid><CT>" triggered "Begin_Bomb_Defuse_With_Kit"
L 04/22/2016 - 19:35:05: "EGM<16><removed Steamid><CT>" triggered "Begin_Bomb_Defuse_With_Kit"
L 04/22/2016 - 19:35:08: "Ratzer<21><removed Steamid><>" triggered "headshot"
L 04/22/2016 - 19:35:08: "Ratzer<21><removed Steamid><>" located on "kill" (position "-125 -1202 -

**Comment by splewis** [comment] 2016-04-22 17:58
It's most likely not related to retakes. You should give actual version info too, aka output of:
- sm version
- sm plugins list

Most people debug crashes using the accerator extension, so you can try using that.

**Comment by Lacrimosa99** [comment] 2016-04-26 16:21
me too.

Metamod:Source version 1.10.7-dev - Build ID: 952:ff9eac3
SourceMod Version: 1.7.3-dev+5303 - Build ID: 5303:6317916

deactivate i the pugin, server mapchange works without crash.
no server error logs (logs are clear).

best regards

**Comment by splewis** [comment] 2016-04-26 17:36
You should still use [accelerator](https://forums.alliedmods.net/showthread.php?t=277703&) if you want any chance at finding the cause.

**Comment by gerrard9099** [comment] 2016-04-26 20:17
Anything else you want me to post from the accelerator? i got this one: https://crash.limetech.org/hr7stzvi4v72

Speak soon, thanks.

**Comment by splewis** [comment] 2016-04-26 20:50
Unfortunately that crash dump doesn't help much. Generally they are much more useful on linux servers.

**Comment by Lacrimosa99** [comment] 2016-04-27 19:19
Log: http://pastebin.com/HFP3X5hC

**Comment by splewis** [comment] 2016-04-27 20:30
I've seen this same crash occur on multi1v1 servers recently as well (example: https://crash.limetech.org/pys6g36bzwag)

Seems to have something to do with a recent CS:GO update.

**Comment by splewis** [comment] 2016-04-28 03:22
Can you say how many rounds were being played on your servers? I.e. the value of ``mp_maxrounds``? (default is 25 or 30 in the retakes_game.cfg file)

I think I know what happened here.
- a bug was reported a few days ago about games going into high round count numbers causing crashes (http://csgo-servers.1073505.n5.nabble.com/Servers-on-Linux-crashing-after-50th-round-td11722.html)
- the CS:GO update tonight addressed this with a fix: "Fixed community server crash relating to graphs and games that go into overtime."
- I never saw this on my retake servers since they go to 25 rounds
- I did see this on my 1v1 servers since they go to 30+ rounds sometimes, but not always


Anyway, hopefully the update tonight fixed this crash.

**Comment by splewis** [comment] 2016-04-30 06:01
From checking the crash.limetech.org results, I don't see any more occurrences of this crash, so I believe it to be fixed now. Let me know if you still experience issues.

**Closed by splewis** 2016-04-30 06:01 UTC
