### ISSUE TITLE
3v4: Spawn on wrong side

### ISSUE THREAD

**Issue by shnytzl** [splewis/csgo-retakes#91] opened 2016-11-22 16:11 UTC
I am trying to user the Retake plugin on a 7 slot server for a 3v4 version. Unfortunately sometimes a CT spawns on the T side. Is there anything I can do? I did the same thing on a 5 slot server for 2v3 and it works there. 

The latest Retake & Metamod/Sourcemod version is used. 
sm_retakes_maxplayers = 7
sm_retakes_ratio_constant = 0.425

**Comment by splewis** [comment] 2017-01-29 05:26
Do you have any way of reproducing this? I've never seen an instance of this in many thousands of rounds. You may have other plugins interfering with retakes.

**Comment by splewis** [comment] 2017-03-12 01:11
Closing since there's still no reproduction steps and I have no evidence of this happening.

**Closed by splewis** 2017-03-12 01:11 UTC
