### ISSUE TITLE
Weapon model missing

### ISSUE THREAD

**Issue by MajorErection** [splewis/csgo-retakes#66] opened 2016-02-26 06:03 UTC
As the title states, sometimes when a new round starts certain people spawn without the weapon model(everything from awp to c4). I'm not even sure if this is caused by this plugin but this problem only occurred after I added this plugin to my servers. Here is my plugin list for both my servers. Hope you can help me :3
>  "Client Preferences" (1.7.3-dev+5289) by AlliedModders LLC
 "Server Advertisement" (2.5) by ESK0
 "Rock The Vote" (1.7.3-dev+5292) by AlliedModders LLC
 "Store - Trade System" (1.0) by Zephyrus
 "Admin Menu" (1.7.3-dev+5289) by AlliedModders LLC
 "CS:GO Retakes" (0.3.0) by splewis
 "Sound Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "SMAC Spinhack Detector" (0.8.5.1) by SMAC Development Team
 "Player Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Basic Ban Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Store - The Resurrection" (1.1) by Zephyrus
 "Basic Chat" (1.7.3-dev+5289) by AlliedModders LLC
 "SMAC Anti-Speedhack" (0.8.5.1) by SMAC Development Team
 "SMAC AutoTrigger Detector" (0.8.5.1) by SMAC Development Team
 "SMAC Command Monitor" (0.8.5.1) by SMAC Development Team
 "SMAC ConVar Checker" (0.8.5.1) by SMAC Development Team
 "Web Shortcuts CS:GO version" (2.4) by Franc1sco franug and James "sslice" Gray
 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
 "Vote Mute/Vote Silence" (1.0.105P) by <eVa>Dog/AlliedModders LLC
 "Anti-Flood" (1.7.3-dev+5289) by AlliedModders LLC
 "Basic Comm Control" (1.7.3-dev+5289) by AlliedModders LLC
 "Admin Help" (1.7.3-dev+5289) by AlliedModders LLC
 "Fun Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "smartbots_blockflashed.smx" smartbots_blockflashed.smx
 "CS:GO Retakes: standard weapon allocator" (0.3.0) by splewis
 "Basic Votes" (1.7.3-dev+5289) by AlliedModders LLC
 "SMAC ESEA Global Banlist" (0.8.5.1) by SMAC Development Team
 "CS:GO Retakes: site picker" (0.3.0) by splewis
 "SMAC Aimbot Detector" (0.8.5.1) by SMAC Development Team
 "Nextmap" (1.7.3-dev+5289) by AlliedModders LLC
 "MapChooser" (1.7.3-dev+5292) by AlliedModders LLC
 "AdminTag" (2.0) by KeepCalm
 "Admin File Reader" (1.7.3-dev+5289) by AlliedModders LLC
 "SourceMod Anti-Cheat" (0.8.5.1) by SMAC Development Team
 "Basic Info Triggers" (1.7.3-dev+5289) by AlliedModders LLC
 "SMAC Eye Angle Test" (0.8.5.1) by SMAC Development Team
 "SMAC Rcon Locker" (0.8.5.1) by SMAC Development Team
 "SMAC Anti-Wallhack" (0.8.5.1) by SMAC Development Team
 "SMAC EAC Global Banlist" (0.8.5.1) by SMAC Development Team
 "Updater" (1.2.2) by GoD-Tony
 "Basic Commands" (1.7.3-dev+5289) by AlliedModders LLC
 "Fun Votes" (1.7.3-dev+5289) by AlliedModders LLC

**Comment by splewis** [comment] 2016-09-10 18:20
I'm closing this since I'm fairly convinced this isn't directly related to retakes, and there's no way to reproduce it.

**Closed by splewis** 2016-09-10 18:20 UTC

**Comment by MajorErection** [comment] 2016-09-11 18:55
yeah sorry bout that, it was another plugin but I forgot I opened this issue. :)
