### ISSUE TITLE
hud show how site retake

### ISSUE THREAD

**Issue by redxxx** [splewis/csgo-retakes#36] opened 2015-10-13 06:37 UTC
https://cloud.githubusercontent.com/assets/613331/5344769/fe494278-7f1a-11e4-9123-33acda4b702d.jpg

like this. can make?

**Comment by splewis** [comment] 2015-10-13 06:40
Sounds like a duplicate of https://github.com/splewis/csgo-retakes/issues/4

**Closed by splewis** 2015-10-13 06:40 UTC
